/************************************************************************
 *****     COPYRIGHT 2000           HONEYWELL LIMITED AUSTRALIA      ****
 ************************************************************************/
#ifndef par_desc_flag
#define par_desc_flag
/*
     paranoiddescriptions.h - Group paranoid descriptions

     Defines paranoid group descriptions

     This file is generated from environ.h and included by environ.h
*/

#define MAXSIZEOFPARADESC	80
struct pardesc
{
    char szName[MAXSIZEOFPARANOIDNAME+1];    // the environment variables name
    char szDescription[MAXSIZEOFPARADESC+1];    // the paranoid groups description
};

#ifdef dynpardll
struct pardesc unixpardescdll[] =
{
	"TASK",   	"Task requesting and handling",
	"QUEUE",   	"Queue handling",
	"SHM",   	"Shared memory",
	"DAT",   	"Data I/O routines",
	"ASCV",   	"ASCII conversion routines and entry points",
	"BYTE",   	"Byte manipulation routines",
	"GHR",   	"Get hardware reference (ie. ipcghr, tdcghr)",
	"HIST",   	"History routines",
	"LOCK",   	"Lock routines",
	"IPSIO",   	"Integrated Personal Station I/O",
	"KEY",   	"Keyed files",
	"CMPRES",   	"Compress routine for displays",
	"IPCIO",   	"IPC PLC I/O",
	"MODBUS",   	"Modbus protocol handling (ie. IPC)",
	"TIME",   	"System time handling",
	"DEVIO",   	"Set raw I/O attributes",
	"ERR",   	"Communications errors and statistics",
	"ARITH",   	"Real arithmetic (ie. fclamp, mzero, ssne)",
	"BIT",   	"Bit manipulations",
	"SEM",   	"Semaphore handling",
	"TDC",   	"TDC routines",
	"GPMAIN",   	"Database I/O and statistics",
	"ALM",   	"Alarm counts (ie. alarm increment, alarm decrement)",
	"CRT",   	"CRT area assignment",
	"PRINT",   	"Printer handling",
	"NIF_MSGQ",   	"Message queue interface routines",
	"NIF_TCP",   	"TCP network interface routines",
	"NIF_AIF",   	"NIF application interface routines",
	"NIF_SYS",   	"General system call errors",
	"NIF_GEN",   	"General NIF routines",
	"NIF_MSG",   	"Message management routines",
	"TRACE",   	"Trace messages",
	"APPLIC",   	"Application programs",
	"R12IO",   	"R1200 and R1200c I/O",
	"LNK",   	"Link routines for dual redundant systems",
	"MODIO",   	"MODICON I/O routines",
	"ABRIO",   	"Allen Bradley I/O routines",
	"KNGIO",   	"King Fisher  I/O routines",
	"PSWIO",   	"Peripheral switch I/O routine",
	"CL",   	"TDC CL compiler interface routines",
	"CHKSUM",   	"Checksum generation routines",
	"IO",   	"General I/O routines",
	"ASEAIO",   	"Asea I/O routines",
	"ULPIO",   	"MicroLPM I/O routines",
	"STRING",   	"String manipulation routines",
	"BBLNK",   	"Bristol Babcock link layer routines",
	"BBNET",   	"Bristol Babcock network layer routines",
	"BBTRN",   	"Bristol Babcock transport layer routines",
	"BBRDB",   	"Bristol Babcock RDB routines",
	"BBRBE",   	"Bristol Babcock RBE routines",
	"BBALM",   	"Bristol Babcock alarm routines",
	"BBSCN",   	"Bristol Babcock scan task routines",
	"DSPLY",   	"Display task and routines",
	"BBTNS",   	"Bristol Babcock transaction routines",
	"BBCFG",   	"Bristol Babcock configurator routines",
	"DUAL_PSW",   	"Dual Redundant PSW software",
	"DUAL_LINK",   	"Dual Redundant link manager software",
	"DUAL_SYNC",   	"Dual Redundant time synchronisation software",
	"DUAL_TIME",   	"Dual Redundant time server software",
	"DUAL_QUEUE",   	"Dual Redundant queue I/F software",
	"DUAL_ONLINE",   	"Dual Redundant online backup software",
	"DUAL_OFFLINE",   	"Dual Redundant offline backup software",
	"SCAN",   	"Scan task software",
	"ECLIO",   	"Excel I/O routines",
	"SQLRPT",   	"SQL report program",
	"LCN",   	"LCN scan task",
	"LICENCE",   	"Licence management",
	"REPORT",   	"Report software",
	"I18N",   	"Internationalisation subsystem",
	"CONFIG",   	"Configuration subsystem",
	"MA5IO",   	"MA500 I/O routines",
	"WINPRT",   	"Win32 printing routines",
	"CONFD",   	"Configuration daemon",
	"CONFD_SELECT",   	"Configuration daemon select subsystem",
	"APPIO",   	"Applicom I/O routines",
	"SQDIO",   	"Square D I/O routines",
	"RAD6500",   	"Rad6500 scan task",
	"RADDAEMON",   	"Rad6500 scan daemon",
	"DEFFILE",   	"Get definition file routines",
	"S90CFG",   	"Series 9000 cfgsum routines",
	"SYSCFG",   	"System config (OS or SCAN/XSM/XFi)",
	"CCTV",   	"CCTV scan tasks",
	"LIGHTS",   	"Lighting control option",
	"G90IO",   	"GE Fanuc series 90 I/O",
	"POINTS",   	"Point database access",
	"DICT",   	"Dictionary access",
	"XDIALUP",   	"XLNET dialup program",
	"ODBC",   	"ODBC interface",
	"NOTCLI",   	"Notifications and alarms client",
	"EVARCH",   	"Extended event archiving",
	"ALARM",   	"Low level alarm manipulation",
	"CDA",   	"Control data access routines",
	"LOGGER",   	"Logger",
	"UMAXIO",   	"UMAX I/O routines",
	"SPPREC",   	"S9000 SPP and recipe paranoids",
	"COPYPROT",   	"Copy protection",
	"UDCCFG",   	"UDC cfgsum routines",
	"UDCDEF",   	"UDC definition file routines",
	"MESSAGE",   	"Message directory access",
	"FBUSIO",   	"Fieldbus routines",
	"BACNET",   	"BACnet server",
	"DFSIO",   	"FS90",
	"OREPORT",   	"Open database reporting",
	"OPC",   	"OPC interface",
	"DFSDMN",   	"FS90 daemon paranoids",
	"ZONE",   	"Zone enforcement",
	"SHIFTMNGR",   	"Shift manager",
	"ACSCFG",   	"Access Configurator",
	"SMS7IO",   	"Siemens S7 interface",
	"MMUIO",   	"Moore mycro 352 I/O routines",
	"ALM_NOTIF",   	"Alarm notification paranoids",
	"FSCIO",   	"FSC routines",
	"SOE",   	"FSCSOE routines",
	"XPC5",   	"XFI - XLNET general",
	"XL5IO",   	"XFI - I/O routines",
	"G80IO",   	"GEM 80 I/O routines",
	"DIALUP",   	"Dialup daemon routines",
	"DMNIO",   	"Daemon I/O routines",
	"IVR",   	"XFI - IVR routines",
	"PGAP",   	"Perimeter global anti-passback routines",
	"H78IO",   	"7800 series burner controller paranoid",
	"OPCIO",   	"OPC client routines",
	"GDA",   	"Generic data access routines",
	"GDALOCK",   	"GDA locking routines",
	"GDALOCAL",   	"GDA local access routines",
	"GDAREM",   	"GDA remote access routines",
	"GDANOTSRV",   	"GDA notification server",
	"GDANOTCLI",   	"GDA notification client",
	"UL",   	"UL listed software",
	"BALYIO",   	"Bailey scan task",
	"ALMPGR",   	"Alarm pager",
	"MSLINKD",   	"Multiple server link daemon",
	"XLSSCN",   	"XLS scan task",
	"XLSDMN",   	"XLS daemon",
	"I9KSCN",   	"Intelliguard 9000 scan task",
	"I9KDMN",   	"Intelliguard 9000 daemon",
	"I9KCFG",   	"Intelliguard 9000 configuration task",
	"CMS",   	"Card Management System",
	"MSVRDF",   	"Multiserver report data factory server",
	"BACSCN",   	"BACnet scan task paranoid",
	"APACIO",   	"Moore APACS routines",
	"CONSVR",   	"Server scripting event connection server",
	"AUTSVR",   	"Server scripting automation server",
	"SCPPKG",   	"Server scripting script package",
	"CHIP",   	"SE chip paranoid",
	"BSIIO",   	"Bristol Babcock open BSI interface",
	"POINTSERVER",   	"PointServer development",
	"DNPSCN",   	"DNP3 top level scantask routines",
	"DNPSCNIO",   	"DNP3 I/O level scantask routines",
	"DNPDMN",   	"DNP3 top level daemon routines",
	"DNPUSR",   	"DNP3 user layer daemon routines",
	"DNPAL",   	"DNP3 application layer daemon routines",
	"DNPTL",   	"DNP3 transport layer daemon routines",
	"DNPDLL",   	"DNP3 data link layer daemon routines",
	"DNPIO",   	"DNP3 device I/O layer daemon routines",
	"TCMIO",   	"Tecom scan task",
	"SQLREP",   	"SQLRep CMS replication task",
	"SCPTSK",   	"Server scripting script manager task",
	"SCPMNGR",   	"Server scripting script manager",
	"SCPPERSIST",   	"Server scripting persistance",
	"SCPEDIT",   	"Server scripting editor",
	"TBLCURSOR",   	"Table Cursor",
	"RSI",   	"RSI Hand Reader",
	"GDASERVER",   	"GDASERVER",
	"GDAOPCIO",   	"GDA OPC client interface",
	"FILREP",   	"File Replication",
	"HSTBCK",   	"History Backfill",
	"NOTIFHOOKAPI",   	"Notification Hook API",
	"DSREDIRECT",   	"DSRedSrv and DSRedCli Redirection",
	"DSDCSRV",   	"DS Network Components server side",
	"DSDCCLI",   	"DS Network Components client side",
	"DSFILEREP",   	"DSFileRepSrv, DSFileRepCli and DSAPI File Replication",
	"DSPNTREP",   	"DSPntRepSrv, DSPntRepCli and DSAPI Point Replication",
	"DSACKSYNC",   	"DSAckSync Alarm and Message Acknowledgement Synching",
	"DSCOMMON",   	"DS Common Libraries",
	"ENERGY",   	"Energy Manager",
	"BCMTOOLS",   	"BizCalc Manager Tools",
	"BCMAUTOVAL",   	"BizCalc Manager Auto Validator",
	"BCMPROCESSOR",   	"BizCalc Manager Processor",
	"BCMSCHEDULER",   	"BizCalc Manager Scheduler",
	"BCMSEQUENCER",   	"BizCalc Manager Sequencer",
	"BCMEVENTPROC",   	"BizCalc Manager Event Processor",
	"BCMMONITOR",   	"BizCalc Manager Monitor",
	"BCMGENERAL",   	"BizCalc Manager General",
	"SQLDB",   	"SQL Database",
	"BCMALGORITHMS",   	"BizCalc Manager Algorithms",
	"ALMEVTATTRIBUTE",   	"alarm/event attributes",
	"NOTIFTRACE",   	"trace alarm/events in notcli/gdanotci",
	"SECURITY",   	"Used by login, and security library routines",
	"WTMGENERAL",   	"Well Test Manager Common & Client",
	"WTMDATA",   	"Well Test Manager Data Access",
	"WTMDEVICE",   	"Well Test Manager Device Access",
	"WTMPROCESSOR",   	"Well Test Manager Processor",
	"WTMSCHEDULER",   	"Well Test Manager Scheduler",
	"HTS",   	"History Tag Synchronization - General",
	"OPCDA",   	"OPC DA interface",
	"OPCAE",   	"OPC AE interface",
	"OPCHDA",   	"OPC HDA interface",
	"GS",   	"Global Schedules",
	"EAFGENERAL",   	"Experion Application Framework - General",
	"EAFCONFIG",   	"Experion Application Framework - Configuration",
	"EAFDESKTOP",   	"Experion Application Framework - Desktop",
	"EAFDIAGNOSTICS",   	"Experion Application Framework - Diagnostics",
	"EAFEVENTS",   	"Experion Application Framework - Events",
	"EAFRPDC",   	"Experion Application Framework - RPDC",
	"EAFSECURITY",   	"Experion Application Framework - Security",
	"EAFSTORAGE",   	"Experion Application Framework - Storage",
	"GDAUSAGE",   	"GDA usage statistics",
	"HTSTAG",   	"History Tag Synchronization - Tag Output",
	"PNTAUDIT",   	"Point audit messages",
	"SYSAUDIT",   	"System audit messages",
	"TAGAUDIT",   	"Tag audit messages",
	"PNTRELAUDIT",   	"Point relation audit messages",
	"AUDIBLE",   	"Annuniciation and silencing paranoids",
	"GCL",   	"CDA-FTW ",
	"CDADATA",   	"CDA-FTW ",
	"CDANOTIF",   	"CDA-FTW ",
	"CDAPLATFORM",   	"CDA-FTW ",
	"ER",   	"CDA-FTW ",
	"SR",   	"CDA-FTW ",
	"CHKPOINT",   	"CDA-FTW ",
	"BOOTP",   	"CDA-FTW ",
	"CTRLLIB",   	"CDA-FTW ",
	"EMDB",   	"CDA-FTW ",
	"BROWSER",   	"CDA-FTW ",
	"NDM",   	"CDA-FTW ",
	"DTL",   	"CDA-FTW ",
	"ICOA",   	"CDA-FTW ",
	"RCOA",   	"CDA-FTW ",
	"OPCG",   	"CDA-FTW ",
	"FUNCTRACE",   	"Function tracing messages",
	"TIMER",   	"Code performance timer and profiling messages",
	"", "" 
};
#endif

#endif	/* end of conditional include par_desc_flag */

/************************************************************************
 *****     COPYRIGHT 2000           HONEYWELL LIMITED AUSTRALIA      ****
 ************************************************************************/
